### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by tuxarch** [ajjames31/i3revenge-iso#1]
sudo: /etc/sudoers.d is owned by uid 1000, should be 0 liveuser is not in the sudoers file. This incedent will be reported.

**Comment by ajjames31** [comment]
This error is possibly caused by permission problems. When building, all of the files in the repo must be copied by root to another directory and the iso built there. I usually make a directory called archiso in my home folder. Then I copy the contents of the github repo to the new directory like this.
sudo cp -r i3revenge/\* ~/archiso
This makes it so that all of the files are owned by root. That is necessary for the archiso build scripts to work correctly, the permissions are then sorted out after the iso is built. I encounted this error before myself. I just built an iso and I did not have the permissions error. I hope this helps. 
I will try to upload a new i3revenge iso to my sourceforge page in the next few days. The url is 
https://sourceforge.net/projects/i3revenge/
